# Generated by Django 5.0.6 on 2024-09-11 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_rendez_vous_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='Date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
